//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatterns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignPatterns.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: &quot;b04b49d8-087c-478b-a39e-445f9cde35f8&quot;,
        ///    &quot;isActive&quot;: true,
        ///    &quot;age&quot;: 22,
        ///    &quot;eyeColor&quot;: &quot;green&quot;,
        ///    &quot;name&quot;: &quot;Alexander Sears&quot;,
        ///    &quot;gender&quot;: &quot;male&quot;,
        ///    &quot;unreadMessage&quot;: 31,
        ///    &quot;phone&quot;: &quot;+1 (857) 433-2192&quot;,
        ///    &quot;address&quot;: &quot;808 Allen Avenue, Courtland, Oregon, 9965&quot;,
        ///    &quot;favoriteFruit&quot;: &quot;strawberry&quot;
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;7073cdb9-3e6e-479c-9b5e-70207d1d4278&quot;,
        ///    &quot;isActive&quot;: true,
        ///    &quot;age&quot;: 25,
        ///    &quot;eyeColor&quot;: &quot;green&quot;,
        ///    &quot;name&quot;: &quot;Serrano Mullins&quot;,
        ///    &quot;gender&quot;: &quot;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
